[package]
name = "kuchiki"
version = "0.3.4"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
license = "MIT"
description = "(朽木) HTML/XML tree manipulation library"
repository = "https://github.com/SimonSapin/kuchiki"

[lib]
name = "kuchiki"
doctest = false

[features]
unstable = [
    "string_cache/unstable",
    "rc/unstable",
    "html5ever/unstable",
    "selectors/unstable",
]

[dependencies]
cssparser = "0.6"
matches = "0.1.2"
html5ever = "0.5.4"
hyper = {version = ">=0.7, <0.10", optional = true}
string_cache = "0.2"
selectors = "0.12"
rc = "0.1.0"

[dev-dependencies]
tempdir = "0.3"
