[package]
name = "kuchiki"
version = "0.5.0"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
license = "MIT"
description = "(朽木) HTML/XML tree manipulation library"
repository = "https://github.com/SimonSapin/kuchiki"

[lib]
name = "kuchiki"
doctest = false

[dependencies]
cssparser = "0.7"
matches = "0.1.4"
html5ever = "0.17"
ref_slice = "1.0"
selectors = "0.15"

[dev-dependencies]
tempdir = "0.3"
